// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olmqcprszzxorgfocppu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sbXFjcHJzenp4b3JnZm9jcHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDc1MDUsImV4cCI6MjA2NzQyMzUwNX0.2auBsznjVbfN4Mp5FKi8kllJ2wU0oguZpawYym3BA1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});